<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Age group' => 'Возраст',
  'Any holiday' => 'Любой',
  'Beauty' => 'Красота и здоровье',
  'Birthday present' => 'День рождения',
  'Chic' => 'Стильный',
  'Developmental' => 'Развивающие',
  'For Holiday' => 'Праздник',
  'For auto' => 'Для авто',
  'For boss' => 'Начальнику',
  'For boss For man' => 'для начальника',
  'For boss For woman' => 'для начальницы',
  'For child' => 'Ребёнку',
  'For child For man' => 'для мальчика',
  'For child For woman' => 'для девочки',
  'For colleague' => 'Сотруднику',
  'For colleague For man' => 'для сотрудника',
  'For colleague For woman' => 'для сотрудницы',
  'For friend' => 'Другу',
  'For friend For man' => 'для друга',
  'For friend For woman' => 'для подруги',
  'For game' => 'Игры и игрушки',
  'For garden' => 'Сад/огород',
  'For grandparent' => 'Бабушке/дедушке',
  'For grandparent For man' => 'для дедушки',
  'For grandparent For woman' => 'для бабушки',
  'For hobby' => 'Для хобби',
  'For home' => 'Для дома',
  'For lover' => 'Любимому/Любимой',
  'For lover For man' => 'для любимого',
  'For lover For woman' => 'для любимой',
  'For office' => 'Для офиса',
  'For parent' => 'Родителям',
  'For parent For man' => 'для папы',
  'For parent For woman' => 'для мамы',
  'For rest' => 'Отдых и развлечения',
  'For soul' => 'Для души',
  'For sport' => 'Спорт и туризм',
  'For yourself' => 'Для себя',
  'For yourself For man' => 'для себя',
  'For yourself For woman' => 'для себя',
  'Funny' => 'Забавный',
  'Holiday name' => 'Повод',
  'House present' => 'Новоселье',
  'Jubilee present' => 'Юбилей',
  'Miracle' => 'Волшебный',
  'No importance' => 'Неважно',
  'Original' => 'Необычный',
  'Repair' => 'Для ремонта',
  'Romantic' => 'Романтичный',
  'Smart' => 'Умный',
  'Souvenir' => 'Сувенир',
  'Technology' => 'Техника',
  'Thanks present' => 'В благодарность',
  'Useful' => 'Практичный',
  'Wedding present' => 'Свадьба',
  'Animate' => 'Живой',
  'Category' => 'Категория',
  'For' => 'Кому',
  'For man' => 'Мужчине',
  'For woman' => 'Женщине',
  'Music' => 'Музыкальный',
  'Price' => 'Цена',
  'Tasty' => 'Вкусный',
  'js_lang_for' => 'var lang_for = {
  woman : {
    ForLover : \'для любимой\',
    ForBoss : \'для начальника\',
    ForChild : \'для девочки\',
    ForGrandparent : \'для бабушки\',
    ForColleague : \'для сотрудницы\',
    ForFriend : \'для подруги\',
    ForParent : \'для мамы\',
    ForOneSef : \'для себя\',
  },
  man : {
    ForLover : \'для любимого\',
    ForBoss : \'для начальника\',
    ForChild : \'для мальчика\',
    ForGrandparent : \'для дедушки\',
    ForColleague : \'для сотрудника\',
    ForFriend : \'для друга\',
    ForParent : \'для папы\',
    ForOneSef : \'для себя\',
  }
};
',
  'submit' => 'Подобрать',
);
