<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '0-1' => 'до 1 года',
  '1-3' => '1-3 года',
  '13-16' => '13-16 лет',
  '17-20' => '17-20 лет',
  '20-30' => '20-30 лет',
  '30-60' => '30-60 лет',
  '4-7' => '4-7 лет',
  '60+' => '60 лет и старше',
  '8-12' => '8-12 лет',
  'Any holiday' => ' ',
  'Birthday present' => 'на День рождения',
  'For boss' => 'боссу',
  'For boss For man' => 'боссу',
  'For boss For woman' => 'боссу',
  'For child' => 'ребёнку',
  'For child For man' => 'мальчику',
  'For child For woman' => 'девочке',
  'For colleague' => 'коллеге',
  'For colleague For man' => 'коллеге',
  'For colleague For woman' => 'коллеге',
  'For friend' => 'другу',
  'For friend For man' => 'другу',
  'For friend For woman' => 'подруге',
  'For grandparent' => 'дедушке или бабушке',
  'For grandparent For man' => 'дедушке',
  'For grandparent For woman' => 'бабушке',
  'For lover' => 'любимому человеку',
  'For lover For man' => 'для любимого',
  'For lover For woman' => 'для любимой',
  'For man' => 'мужчине',
  'For parent' => 'для родителей',
  'For parent For man' => 'папе',
  'For parent For woman' => 'маме',
  'For woman' => 'женщине',
  'For yourself' => 'себе',
  'For yourself For man' => 'себе',
  'For yourself For woman' => 'себе',
  'House present' => 'на новоселье',
  'Jubilee present' => 'на юбилей',
  'No importance' => ' ',
  'Thanks present' => 'в благодарность',
  'Wedding present' => 'на день свадьбы',
  'gifts' => 'Подарки',
);
